/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
#include <time.h>


int main(int argc, char *argv[])
{
	char *host;
	CLIENT *clnt;
	

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
		host = argv[1];

	int primero=0;
	int segundo=0;
	

	printf("Introduzca el primer operando: ");
	scanf("%i",&primero);
	while(abs(primero) > 9){
		printf("Introduzca el primer operando: ");
		scanf("%d",&primero);
	}
	
	printf("Introduzca el segundo operando: ");
	scanf("%i",&segundo);
	while(abs(segundo) > 9){
		printf("Introduzca el segundo operando");
		scanf("%d",&segundo);
	}

	operandos operands = {primero, segundo};
	
	#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
	#endif

	int *result;
	int resultado_total=0;
	clock_t principio = clock();

	for(int i = 0; i < 100000; i++){
		result = suma_1(&operands, clnt);
		if (result == (int *)NULL)
			clnt_perror(clnt, "call failed");
		resultado_total += *result;
	}

	clock_t fin = clock();
	double tiempo = (double) (fin-principio) / CLOCKS_PER_SEC;
	
	printf("El resultado es: %i\n", resultado_total);
	printf("El tiempo es %f segundos\n", tiempo);

	

	exit(0);
}
