#!/bin/bash

#Mostrar películas
echo -e "\n\t1) Mostrar pelis en el formato indicado"
sed -e 's/<p id=.director.>/Director: /g' -e 's/<p id=.genres.>/Generos: /g' -e 's/<. id="writers">/Guionistas: /g' -e 's/<.2>/Titulo: /g' -e 's/<p id="rating">/Valoracion: /g' -e 's/<p id=.length.>/Duracion: /g' -e 's/m<\/p>/ minutos/g' -e 's/<\/p>//g' -e 's/<p>/Sinopsis: /g' -e 's/<p>/Sinopsis: /g' -e '/<\/article>/d' -e '/<hr>/d' -e 's/<article>/\t==================================/g' -e 's/(20/\n\t\tAño: 20/g' -e 's/)<\/h2>/ /g' -e '/<\/body>/d' -e '/<\/html>/d' -e '/<!DOCTYPE html>/d' -e '/html/d' -e '/<head>/d' -e '/<title>Films<\/title>/d' -e '/<\/head>/d' -e '/<body>/d' -e '/<h1>Films<\/h1>/d' -e 's/[|]/, /g' -e 's/ratings/valoraciones/g' films.html

#Mostrar titulo, año y valoracion
echo -e "\n\t2) Mostrar el título, el año y la valoración de las películas de los años 2000 (2000-2009)\n"
sed -e 's/<p id=.director.>/Director: /g' -e 's/<p id=.genres.>/Generos: /g' -e 's/<. id="writers">/Guionistas: /g' -e 's/<.2>/Titulo: /g' -e 's/<p id="rating">/Valoracion: /g' -e 's/<p id=.length.>/Duracion: /g' -e 's/m<\/p>/ minutos/g' -e 's/<\/p>//g' -e 's/<p>/Sinopsis: /g' -e 's/<p>/Sinopsis: /g' -e '/<\/article>/d' -e '/<hr>/d' -e 's/<article>/\t==================================/g' -e 's/(20/\n\t\tAño: 20/g' -e 's/)<\/h2>/ /g' -e '/<\/body>/d' -e '/<\/html>/d' -e '/<!DOCTYPE html>/d' -e '/html/d' -e '/<head>/d' -e '/<title>Films<\/title>/d' -e '/<\/head>/d' -e '/<body>/d' -e '/<h1>Films<\/h1>/d' -e 's/[|]/, /g' -e 's/ratings/valoraciones/g' films.html | grep -B 1 -A 1 '200[0-9]'

#Mostrar 
echo -e "\n\n\t3)  Mostrar las películas formatadas como en el punto 1 pero cambiando el formato del numero de valoraciones de 1000 a 1k\n"
sed -e 's/<p id=.director.>/Director: /g' -e 's/<p id=.genres.>/Generos: /g' -e 's/<. id="writers">/Guionistas: /g' -e 's/<.2>/Titulo: /g' -e 's/<p id="rating">/Valoracion: /g' -e 's/<p id=.length.>/Duracion: /g' -e 's/m<\/p>/ minutos/g' -e 's/<\/p>//g' -e 's/<p>/Sinopsis: /g' -e 's/<p>/Sinopsis: /g' -e '/<\/article>/d' -e '/<hr>/d' -e 's/<article>/\t==================================/g' -e 's/(20/\n\t\tAño: 20/g' -e 's/)<\/h2>/ /g' -e '/<\/body>/d' -e '/<\/html>/d' -e '/<!DOCTYPE html>/d' -e '/html/d' -e '/<head>/d' -e '/<title>Films<\/title>/d' -e '/<\/head>/d' -e '/<body>/d' -e '/<h1>Films<\/h1>/d' -e 's/[|]/, /g' -e 's/ratings/valoraciones/g' -e 's/\([[:digit:]]\{3\}\)\([[:digit:]]\{3\}\)/\1\k/g' films.html

echo -e "\n\n\t4) Añadir un punto al final de las líneas que no lo tengan.\n"
sed -e 's/<p id=.director.>/Director: /g' -e 's/<p id=.genres.>/Generos: /g' -e 's/<. id="writers">/Guionistas: /g' -e 's/<.2>/Titulo: /g' -e 's/<p id="rating">/Valoracion: /g' -e 's/<p id=.length.>/Duracion: /g' -e 's/m<\/p>/ minutos/g' -e 's/<\/p>//g' -e 's/<p>/Sinopsis: /g' -e 's/<p>/Sinopsis: /g' -e '/<\/article>/d' -e '/<hr>/d' -e 's/<article>/\t==================================/g' -e 's/(20/\n\t\tAño: 20/g' -e 's/)<\/h2>/ /g' -e '/<\/body>/d' -e '/<\/html>/d' -e '/<!DOCTYPE html>/d' -e '/html/d' -e '/<head>/d' -e '/<title>Films<\/title>/d' -e '/<\/head>/d' -e '/<body>/d' -e '/<h1>Films<\/h1>/d' -e 's/[|]/, /g' -e 's/ratings/valoraciones/g' -e 's/$/\./g' films.html

echo -e "\n\n\t5) Mostrar una versión resumida en la que la sinopsis se limita a 300 caracteres y añadiendo ... al final\n"
sed -e 's/<p id=.director.>/Director: /g' -e 's/<p id=.genres.>/Generos: /g' -e 's/<. id="writers">/Guionistas: /g' -e 's/<.2>/Titulo: /g' -e 's/<p id="rating">/Valoracion: /g' -e 's/<p id=.length.>/Duracion: /g' -e 's/m<\/p>/ minutos/g' -e 's/<\/p>//g' -e 's/<p>/Sinopsis: /g' -e 's/<p>/Sinopsis: /g' -e '/<\/article>/d' -e '/<hr>/d' -e 's/<article>/\t==================================/g' -e 's/(20/\n\t\tAño: 20/g' -e 's/)<\/h2>/ /g' -e '/<\/body>/d' -e '/<\/html>/d' -e '/<!DOCTYPE html>/d' -e '/html/d' -e '/<head>/d' -e '/<title>Films<\/title>/d' -e '/<\/head>/d' -e '/<body>/d' -e '/<h1>Films<\/h1>/d' -e 's/[|]/, /g' -e 's/ratings/valoraciones/g' films.html | sed -e 's/^\(.\{318\}\).*$/\1.../'