/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int calculadora_prog_1(char *host, char *operation, struct operandos operands)
{
	CLIENT *clnt;
	int *result;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	if (strcmp(operation, "SUMA") == 0)
	{
		result = suma_1(&operands, clnt);
		if (result == (int *)NULL)
			clnt_perror(clnt, "call failed");
	}
	else if (strcmp(operation, "RESTA") == 0)
	{
		result = resta_1(&operands, clnt);
		if (result == (int *)NULL)
			clnt_perror(clnt, "call failed");
	}
	else if (strcmp(operation, "MULTIPLICACION") == 0)
	{
		result = multiplicacion_1(&operands, clnt);
		if (result == (int *)NULL)
			clnt_perror(clnt, "call failed");
	}
	else if (strcmp(operation, "DIVISION") == 0)
	{
		result = division_1(&operands, clnt);
		if (result == (int *)NULL)
			clnt_perror(clnt, "call failed");
	}
	else
		return 0;

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	return *result;
}

int main(int argc, char *argv[])
{
	char *host;

	struct operandos operands;
	char operation[10];

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}

	printf("Introduzca el primer operando: ");
	scanf("%i", &operands.a);
	printf("Introduzca el segundo operando: ");
	scanf("%i", &operands.b);
	printf("Introduzca la operacion: ");
	scanf("%s", operation);

	host = argv[1];
	int result = calculadora_prog_1(host, operation, operands);

	printf("El resultado es: %i\n", result);

	exit(0);
}
